name: OpenApi Checks

on:
  pull_request:
    branches:
      - master

jobs:
  checks:    
    runs-on: ubuntu-latest
    steps:   
      - uses: TechnicalFreak/fop.openapi-rules/.github/workflows/check-openapi.yaml@5
        with:
          rule-version: 2
          openapi-file-path: 'my-api.yaml'

