name: OpenApi Checks

on:
  pull_request:
    branches:
      - master

jobs:
  OWASP-CHECK:    
    runs-on: ubuntu-latest
    steps:   
      - uses: https://raw.githubusercontent.com/TechnicalFreak/fop.openapi-rules/3/github/actions/check-openapi/action.yml@3
        with:
          rule-version: 2
          openapi-file-path: 'my-api.yaml'

