name: OpenApi Checks

on:
  pull_request:
    branches:
      - master

jobs:
  checks:    
    uses: TechnicalFreak/fop.openapi-rules/.github/workflows/check-openapi.yaml@13
    with:
      openapi-file-path: 'my-api.yaml'

