name: OpenApi Checks

on:
  pull_request:
    branches:
      - master

env:
  OPENAPI_FILE_PATH: my-api.yaml

jobs:
  check:
    uses: TechnicalFreak/fop.openapi-rules/.github/workflows/check-openapi.yaml@16
    with:
      openapi-file-path: $OPENAPI_FILE_PATH
