name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
       - 'master'

jobs:
  Release:    
    runs-on: ubuntu-latest
    steps:      
      - name: Print GitHub Action Variables
        run: |
          for var in $(compgen -e); do
            echo "$var: ${!var}"
          done